name: Generate Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./
          output_dir: ./docs
          front_page: DOCS.md
          
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.3.0
