    - uses: actions/checkout@v2
      with:
         ref: main

    - name: Screenshot Website
      uses: swinton/screenshot-website@v1.x
      with:
        width: 1920
        source: https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/
        destination: screenshot.png
        full-page: true
        delay: 100

    - uses: actions/download-artifact@v2
      with:
        name: screenshot

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: update screenshot
        branch: main
        file_pattern: screenshot.png

    - name: Clean
      uses: GeekyEggo/delete-artifact@v1.0.0
      with:
        name: screenshot
